food/urls.py
from . import views
from django.urls import path


app_name = 'food'

urlpatterns = [
    #food
    # path('', views.index, name='index'),
    #food_classbased
    path('', views.indexClassView.as_view(),name='index'),

    #detail
    # path('<int:item_id>/',views.detail, name='detail'),
    #detail_classbased
    path('<int:pk>/',views.foodDetail.as_view(), name='detail'),

    #add items
    # path('add/',views.create_item,name='create_item'),
    #class_based_additem
    path('add/',views.createItem.as_view(),name='create_item'),


    #update_item
    path('edit/<int:item_id>/',views.update_item,name='update_item'),
    #delete_item
    path('delete/<int:item_id>/',views.delete_item,name='delete_item'),


    # path('item/', views.item, name='item'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout/', user_views.logout_view, name='logout'),
    path('profile/', user_views.profilepage, name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Items(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://static.wixstatic.com/media/bf242e_6133b4ae6a104cc2b50d70179f35efea~mv2.jpg/v1/fill/w_500,h_376,al_c,lg_1,q_80,enc_auto/food-placeholder.jpg")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.png',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Items

class itemForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Items
from django.template import loader
from .forms import itemForm

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

# Function_base_index

def index(request):
    item_list = Items.objects.all()
    # template = loader.get_template('food/index.html')
    # context = {
    #     'item_list':item_list,
    # }
    # # return HttpResponse(template.render(context,request))
    return render(request,'food/index.html',{'item_list':item_list})

# Class_based_index

class indexClassView(ListView):
    model = Items;
    template_name = 'food/index.html';
    context_object_name = 'item_list';


# Function_base_detail

def detail(request,item_id):

    item = Items.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)

# Class_based_detail

class foodDetail(DetailView):
    model = Items;
    template_name = 'food/detail.html';



def create_item(request):

    form = itemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form})

# this is class based view for create view

class createItem(CreateView):
    model = Items;
    fields = ['item_name','item_desc','item_price','item_image']

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)
    template_name = 'food/item-form.html'

def update_item(request,item_id):

    item = Items.objects.get(id=item_id)
    form = itemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,item_id):

    item = Items.objects.get(id=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item_delete.html',{'item':item})

users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.generic import TemplateView

from .forms import RegisterForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('food:index')

    return render(request, 'users/logout.html')

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand"  href="{% url 'food:index' %}">FoodApp</a>
        <div class="navbar">
            <a style="margin-right: 10px; color: #3b7ae8  !important;" class="nav-item nav-link text-light" href="{% url 'food:create_item' %}">Add Item</a>
            <a style="margin-right: 10px; color: #3b7ae8  !important;" class="nav-item nav-link text-light" href="#">Delete Item</a>
            <a style="margin-right: 10px; color: #3b7ae8  !important;" class="nav-item nav-link text-light" href="#">View Item</a>
            
            
            

            {% if user.is_authenticated %}
                <!-- <a style="margin-right: 10px; color: #3b7ae8" href="{% url 'logout' %}">logout</a> -->
                <a style="margin-right: 10px; color: #3b7ae8  !important;" class="nav-item nav-link text-light" href="{% url 'logout' %}">Logout</a>
                <a style="margin-right: 10px; color: #3b7ae8  !important;" class="nav-item nav-link text-light" href="{% url 'profile' %}">Profile</a>
            {% else %}
                <!-- <a style="margin-right: 10px; color: #3b7ae8" href="{% url 'login' %}">Login</a> -->
                <a style="margin-right: 10px; color: #3b7ae8  !important;" class="nav-item nav-link text-light" href="{% url 'login' %}">Login</a>
            {% endif %}

        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}


    {% block body %}
    {% endblock %}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    {% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="card" style="height:300px" src="{{object.item_image}}">
            </div>
            <div class="col-md-6">
                <h1>{{ object.item_name }}</h1>
                <h2>{{ object.item_desc }}</h2>
                <h2>{{ object.item_price }}</h2>
                <a href="{% url 'food:delete_item' object.id %}">Delete</a>
            </div>
        </div>
    </div>


    {% endblock %}
</body>

</html>

food/templates/food/index.html
{% extends 'food/base.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% block body %}

{% for a in item_list %}

<div class="row">
    <div class="col-md-3 offset-md-2">
        <img class="card" style=" height:150px" src="{{ a.item_image}}"/>
    </div>
    <div class="col-md-4">
        <h3>{{a.item_name}}</h3>
        <h5>{{a.item_desc}}</h5>
        <h6>${{a.item_price}}</h6>
        <h6>Added by {{ a.user_name }}</h6>
    </div>
    <div class="col-md-2">
        <a href="{% url 'food:detail' a.id %}" class="btn btn-success">Details</a>
        <a href="{% url 'food:update_item' a.id %}" class="btn btn-success">Edit</a>
    </div>
</div>


{% endfor %}

{% endblock %}



</body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                    <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label }} <br>
                                {{ field }} <br>
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
</body>
</html>

food/templates/food/item_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    <h2> Are you sure you want to delete the item {{ item.item_name }} </h2>
    <button type="submit">Confirm</button>
</form>
</body>
</html>

users/templates/users/login.html
{% extends 'food/base.html' %}
 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                    <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}
</body>
</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    <h1> Are you sure you want to logout?</h1>
    <button type="submit">Yes</button>

</form>

</body>
</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{ user.username }}<h1>
<img width="150px" height="150px" src="{{ user.profile.image.url }}">
</body>
</html>

users/templates/users/register.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                    <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label }} <br>
                                {{ field }} <br>
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
</body>
</html>